import tkinter as tk

def reset_widget(widget):
    for child in widget.winfo_children():
        reset_widget(child) 
        child.destroy()


def attach_tooltip(widget, text, delay=150):
    # Generated by ChatGPT
    tooltip = {"win": None, "after_id": None}

    def show_tooltip():
        if tooltip["win"] is not None:
            return
        tw = tk.Toplevel(widget)
        tw.wm_overrideredirect(True)
        x = widget.winfo_rootx() + 10
        y = widget.winfo_rooty() + 20
        tw.wm_geometry(f"+{x}+{y}")
        lbl = tk.Label(tw, text=text, relief="solid", borderwidth=1, padx=4, pady=2)
        lbl.pack()
        tooltip["win"] = tw # type: ignore

    def on_enter(event):
        if tooltip["after_id"]:
            widget.after_cancel(tooltip["after_id"])
        tooltip["after_id"] = widget.after(delay, show_tooltip)

    def on_leave(event):
        if tooltip["after_id"]:
            widget.after_cancel(tooltip["after_id"])
            tooltip["after_id"] = None
        if tooltip["win"] is not None:
            tooltip["win"].destroy()
            tooltip["win"] = None

    # Bind both Enter and Motion for reliability
    widget.bind("<Enter>", on_enter)
    widget.bind("<Motion>", on_enter)
    widget.bind("<Leave>", on_leave)


def copy_to_clipboard(widget, text: str):
    widget.clipboard_clear()
    widget.clipboard_append(text)


def display_error_window(widget, title: str, err: str, info: str = ""):
    """ 
    (Currently) a simple error reporting GUI
    """
    win = tk.Toplevel(widget)
    win.title(title)
    win.geometry("500x360")
    win.transient(widget)
    win.grab_set()
    
    tk.Label(win, text=err, fg="red", font=('Arial', 12)).pack()
    
    if info:
        tk.Label(win, text=info).pack()
        
    tk.Label(win, text="Close this window to continue.", font=('Arial', 7)).pack()
