import tkinter as tk
from tkinter import messagebox

def reset_widget(widget):
    for child in widget.winfo_children():
        reset_widget(child) 
        child.destroy()


def attach_tooltip(widget, text, delay=150):
    # Generated by ChatGPT
    tooltip = {"win": None, "after_id": None}

    def show_tooltip():
        if tooltip["win"] is not None:
            return
        tw = tk.Toplevel(widget)
        tw.wm_overrideredirect(True)
        x = widget.winfo_rootx() + 10
        y = widget.winfo_rooty() + 30
        tw.wm_geometry(f"+{x}+{y}")
        lbl = tk.Label(tw, text=text, relief="solid", borderwidth=1, padx=4, pady=2)
        lbl.pack()
        tooltip["win"] = tw # type: ignore

    def on_enter(event):
        if tooltip["after_id"]:
            widget.after_cancel(tooltip["after_id"])
        tooltip["after_id"] = widget.after(delay, show_tooltip)

    def on_leave(event):
        if tooltip["after_id"]:
            widget.after_cancel(tooltip["after_id"])
            tooltip["after_id"] = None
        if tooltip["win"] is not None:
            tooltip["win"].destroy()
            tooltip["win"] = None

    # Bind both Enter and Motion for reliability
    widget.bind("<Enter>", on_enter)
    widget.bind("<Motion>", on_enter)
    widget.bind("<Leave>", on_leave)


def copy_to_clipboard(widget, text: str):
    widget.clipboard_clear()
    widget.clipboard_append(text)
    messagebox.showinfo(title="Text copied!", message=f"Copied\n\"{text}\"to clipboard.")

def center_popup(parent, win):
    win.update_idletasks()
    
    parent_x = parent.winfo_rootx()
    parent_y = parent.winfo_rooty()
    parent_w = parent.winfo_width()
    parent_h = parent.winfo_height()

    win_w = win.winfo_reqwidth()
    win_h = win.winfo_reqheight()

    # Calculate centered position
    x = parent_x + (parent_w // 2) - (win_w // 2)
    y = parent_y + (parent_h // 2) - (win_h // 2)

    win.geometry(f"+{x}+{y}")
    
    
def add_hover_effect(btn, normal_bg, hover_bg):

    def on_enter(e):
        btn.configure(bg=hover_bg, activebackground=hover_bg)

    def on_leave(e):
        btn.configure(bg=normal_bg, activebackground=normal_bg)

    btn.bind("<Enter>", on_enter)
    btn.bind("<Leave>", on_leave)